server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.153.102.191:3306/spaceflight?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ma.vns.pojo
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true